# Generated by Django 6.0.2 on 2026-03-02 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('jp', 'Japanese')], default='en', max_length=2)),
                ('word', models.CharField(max_length=200)),
                ('reading', models.CharField(blank=True, max_length=200)),
                ('meaning', models.TextField()),
                ('word_type', models.CharField(blank=True, max_length=20)),
                ('example', models.TextField(blank=True)),
                ('mastery', models.PositiveSmallIntegerField(choices=[(0, 'Chưa nhớ'), (1, 'Đang học'), (2, 'Thành thạo')], default=0)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'word', 'lang')},
            },
        ),
    ]
