# Generated by Django 5.0.6 on 2026-03-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_fileupload_quiz_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='reading',
            new_name='pronunciation',
        ),
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('import', 'Import')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='word',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('ja', 'Japanese')], default='en', max_length=2),
        ),
    ]
